backend:
  name: github
  repo: Viguro79/pmequitherapie
  branch: feat/workinprogress
  base_url: https://sveltia-cms-auth.vincent-guerinrousteau.workers.dev
media_folder: "images"
public_folder: "/images"

collections:
  - name: "pages"
    label: "Pages"
    files:
      - label: "À propos"
        name: "apropos"
        file: "apropos.md"
        fields:
          - { label: "Titre", name: "title", widget: "string" }
          - { label: "Contenu", name: "body", widget: "markdown" }
      - label: "Accueil"
        name: "home"
        file: "index.md"
        fields:
          - { label: "Titre", name: "title", widget: "string" }
          - { label: "Apropos", name: "apropos", widget: "object", fields: 
              [
                { label: "Titre", name: "titre", widget: "string" },
                { label: "Texte", name: "texte", widget: "text" },
                { label: "Bouton", name: "bouton", widget: "object", fields: [
                  { label: "URL", name: "url", widget: "string" },
                  { label: "Texte", name: "texte", widget: "string" }
                ]}
              ]
            }
          - { label: "Features", name: "features", widget: "list", fields: [
              { label: "Icône", name: "icon", widget: "string" },
              { label: "Titre", name: "titre", widget: "string" },
              { label: "Texte", name: "texte", widget: "list", required: false },
              { label: "Liste", name: "liste", widget: "list", required: false },
              { label: "URL", name: "url", widget: "string", required: false }
            ]
          }
      - label: "Équithérapie"
        name: "equitherapie"
        file: "equitherapie.md"
        fields:
          - { label: "Titre", name: "title", widget: "string" }
          - { label: "Contenu", name: "body", widget: "markdown" }
      - label: "Informations pratiques"
        name: "infos"
        file: "infos.md"
        fields:
          - { label: "Titre", name: "title", widget: "string" }
          - { label: "Contenu", name: "body", widget: "markdown" }
      - label: "Liens utiles"
        name: "liens"
        file: "liens.md"
        fields:
          - { label: "Titre", name: "title", widget: "string" }
          - { label: "Contenu", name: "body", widget: "markdown" }
      - label: "Contact"
        name: "contact"
        file: "contact.md"
        fields:
          - { label: "Titre", name: "title", widget: "string" }
          - { label: "Téléphone", name: "phone", widget: "string", required: true }
          - { label: "Contenu", name: "body", widget: "markdown" }